EXEC InsertSchool 'BHEKIMFUNDO PRIMARY SCHOOL',2,1
EXEC InsertSchool 'EMMANGWENI PRIMARY SCHOOL',2,1
EXEC InsertSchool 'IGAGASI PRIMARY SCHOOL',2,1
EXEC InsertSchool 'ASSER MALOKA SECONDARY SCHOOL',2,2
EXEC InsertSchool 'DAWNVIEW HIGH SCHOOL',2,2
EXEC InsertSchool 'DUMEHLEZI INTERMEDIATE SCHOOL',2,4
EXEC InsertSchool 'MARINE PRIMARY SCHOOL',3,1
EXEC InsertSchool 'WESTCOTT PRIMARY SCHOOL',3,1
EXEC InsertSchool 'BELLVILLE HOËR TEGNIESE SKOOL',3,2
EXEC InsertSchool 'DE TUINEN PRIMÊRE SKOOL',3,1
EXEC InsertSchool 'GOEDVERWACHT MOR PRIMÊRE SKOOL',3,1
EXEC InsertSchool 'SANDANEZWE EDUCARE',3,1
EXEC InsertSchool 'MAOKENG PRIMARY SCHOOL',4,1
EXEC InsertSchool 'RABUGALE PRIMARY SCHOOL',4,1
EXEC InsertSchool 'THABO MBEKI PRIMARY SCHOOL',4,1
EXEC InsertSchool 'DIMPE SECONDARY SCHOOL',4,2
EXEC InsertSchool 'MATHULASERA SECONDARY SCHOOL',4,2
EXEC InsertSchool 'LAERSKOOL ALMA',4,1
EXEC InsertSchool 'MATHINTHA INTERMEDIATE',4,4
EXEC InsertSchool 'MADIBENG PRIMARY SCHOOL',5,1
EXEC InsertSchool 'MOOKI-LOBELO PRIMARY SCHOOL',5,1
EXEC InsertSchool 'VISISANI PRIMARY SCHOOL',5,1
EXEC InsertSchool 'HOMEVALE SECONDARY SCHOOL NR 1',5,2
EXEC InsertSchool 'CONCORDIA SEKONDÊRE SKOOL',5,2
EXEC InsertSchool 'KEIMOES GEKOMBINEERDE SKOOL',5,3
EXEC InsertSchool 'SIVIWE SENIOR PRIMARY SCHOOL',6,1
EXEC InsertSchool 'ST GEORGES PRIMARY SCHOOL',6,1
EXEC InsertSchool 'WODEHOUSE JUNIOR SECONDARY SCHOOL',6,2
EXEC InsertSchool 'ZIGADINI JUNIOR SECONDARY SCHOOL',6,2
EXEC InsertSchool 'BLESS FARM SCHOOL',6,3
EXEC InsertSchool 'BESTERSVLEI PF/S',7,1
EXEC InsertSchool 'BODIKELA',7,2
EXEC InsertSchool 'CLUBVIEW S/S',7,3
EXEC InsertSchool 'EE MONESE C/S',7,3
EXEC InsertSchool 'FOURIESBURG I/S',7,4
EXEC InsertSchool 'ITEBOHELENG P/S',7,1
EXEC InsertSchool 'KGUTLISO P/S',7,1
EXEC InsertSchool 'EKUPHUMULENI PRIMARY SCHOOL',8,1
EXEC InsertSchool 'EMBUZANE PRIMARY SCHOOL',8,1
EXEC InsertSchool 'HABILE PRIMARY SCHOOL',8,1
EXEC InsertSchool 'CHIEF AMPIE MAYISA SECONDARY SCHOOL',8,2
EXEC InsertSchool 'HOËRSKOOL PIET RETIEF',8,3
EXEC InsertSchool 'ENKONENI PRIMARY SCHOOL',9,1
EXEC InsertSchool 'MATHONSI PRIMARY SCHOOL',9,1
EXEC InsertSchool 'NKUNGUMATHE PRIMARY SCHOOL',9,1
EXEC InsertSchool 'NONIKELA PRIMARY SCHOOL',9,1
EXEC InsertSchool 'HIGHLANDS JUNIOR SECONDARY SCHOOL',9,2
EXEC InsertSchool 'DOLO COMBINED SCHOOL',9,3
EXEC InsertSchool 'LETLHAKANE PRIMARY SCHOOL',10,1
EXEC InsertSchool 'MONTSAMAISA PRIMARY SCHOOL',10,1
EXEC InsertSchool 'GABORONE SECONDARY SCHOOL',10,2
EXEC InsertSchool 'SEDIBELO SECONDARY SCHOOL',10,2
